echo "HTTP/1.1 200 OK ";
echo "Content-Type: text/html;";
echo "Content-Length: 335";
echo "Connection: keep-alive";
echo "";
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";
echo "  <head>";
echo "        <meta charset=\"UTF-8\">";
echo "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">";
echo "        <title>My Website</title>";
echo "  </head>";
echo "  <body>";
echo "        <main>";
date;
echo "        </main>";
echo "  </body>";
echo "</html>";
